export const refsLines = {
  // <-- ------------------ West America Lines ------------------ -->
  westNaAsiaL: document.querySelector('.westNaAsiaL'),
  westNaAsiaM: document.querySelector('.westNaAsiaM'),
  westNaAsiaS: document.querySelector('.westNaAsiaS'),
  westNaEuropeL: document.querySelector('.westNaEuropeL'),
  westNaEuropeM: document.querySelector('.westNaEuropeM'),
  westNaEuropeS: document.querySelector('.westNaEuropeS'),
  westNaNorthL: document.querySelector('.westNaNorthL'),
  westNaNorthM: document.querySelector('.westNaNorthM'),
  westNaNorthS: document.querySelector('.westNaNorthS'),
  westNaOceaniaL: document.querySelector('.westNaOceaniaL'),
  westNaOceaniaM: document.querySelector('.westNaOceaniaM'),
  westNaOceaniaS: document.querySelector('.westNaOceaniaS'),
  westNaSouthL: document.querySelector('.westNaSouthL'),
  westNaSouthM: document.querySelector('.westNaSouthM'),
  westNaSouthS: document.querySelector('.westNaSouthS'),

  // <-- ------------------ East America Lines ------------------ -->
  eastNaAsiaL: document.querySelector('.eastNaAsiaL'),
  eastNaAsiaM: document.querySelector('.eastNaAsiaM'),
  eastNaAsiaS: document.querySelector('.eastNaAsiaS'),
  eastNaEuropeL: document.querySelector('.eastNaEuropeL'),
  eastNaEuropeM: document.querySelector('.eastNaEuropeM'),
  eastNaEuropeS: document.querySelector('.eastNaEuropeS'),
  eastNaNorthL: document.querySelector('.eastNaNorthL'),
  eastNaNorthM: document.querySelector('.eastNaNorthM'),
  eastNaNorthS: document.querySelector('.eastNaNorthS'),
  eastNaOceaniaL: document.querySelector('.eastNaOceaniaL'),
  eastNaOceaniaM: document.querySelector('.eastNaOceaniaM'),
  eastNaOceaniaS: document.querySelector('.eastNaOceaniaS'),
  eastNaSouthL: document.querySelector('.eastNaSouthL'),
  eastNaSouthM: document.querySelector('.eastNaSouthM'),
  eastNaSouthS: document.querySelector('.eastNaSouthS'),

  // <-- -------------------- Germany Lines --------------------- -->
  germanyAsiaL: document.querySelector('.germanyAsiaL'),
  germanyAsiaM: document.querySelector('.germanyAsiaM'),
  germanyAsiaS: document.querySelector('.germanyAsiaS'),
  germanyEuropeL: document.querySelector('.germanyEuropeL'),
  germanyEuropeM: document.querySelector('.germanyEuropeM'),
  germanyEuropeS: document.querySelector('.germanyEuropeS'),
  germanyNorthL: document.querySelector('.germanyNorthL'),
  germanyNorthM: document.querySelector('.germanyNorthM'),
  germanyNorthS: document.querySelector('.germanyNorthS'),
  germanyOceaniaL: document.querySelector('.germanyOceaniaL'),
  germanyOceaniaM: document.querySelector('.germanyOceaniaM'),
  germanyOceaniaS: document.querySelector('.germanyOceaniaS'),
  germanySouthL: document.querySelector('.germanySouthL'),
  germanySouthM: document.querySelector('.germanySouthM'),
  germanySouthS: document.querySelector('.germanySouthS'),

  // <-- ------------------- Singapore Lines -------------------- -->
  singaporeAsiaL: document.querySelector('.singaporeAsiaL'),
  singaporeAsiaM: document.querySelector('.singaporeAsiaM'),
  singaporeAsiaS: document.querySelector('.singaporeAsiaS'),
  singaporeEuropeL: document.querySelector('.singaporeEuropeL'),
  singaporeEuropeM: document.querySelector('.singaporeEuropeM'),
  singaporeEuropeS: document.querySelector('.singaporeEuropeS'),
  singaporeNorthL: document.querySelector('.singaporeNorthL'),
  singaporeNorthM: document.querySelector('.singaporeNorthM'),
  singaporeNorthS: document.querySelector('.singaporeNorthS'),
  singaporeOceaniaL: document.querySelector('.singaporeOceaniaL'),
  singaporeOceaniaM: document.querySelector('.singaporeOceaniaM'),
  singaporeOceaniaS: document.querySelector('.singaporeOceaniaS'),
  singaporeSouthL: document.querySelector('.singaporeSouthL'),
  singaporeSouthM: document.querySelector('.singaporeSouthM'),
  singaporeSouthS: document.querySelector('.singaporeSouthS'),
};
