export const store = {
  status: 0,
  sAmericaUsers: 0,
  nAmericaUsers: 0,
  europeUsers: 0,
  australiaUsers: 0,
  asiaUsers: 0,
  blueServer: false,
  numberOfServers: 0,
  naFirstServer: false,
  naSecondServer: false,
  europeServer: false,
  asiaServer: false,
  byteCloudHtml: `<li><h2 class="list_title">ByteCloud</h2></li>`,
  objectStorageHtml: `<li><h2 class="list_title">Object Storage</h2></li>`,
};
